# -*- coding: utf-8 -*-
"""code_datasettt_(1) (4).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18deVU2t0C7uxbrhp9QNrDILK2HQRvp9N
"""

import numpy as np
import pandas as pd
import io

from google.colab import files

uploaded = files.upload()

mydata= pd.read_csv(io.BytesIO(uploaded['test.csv']),header=None)

mydata_array = np.array(mydata)

mydata_array.shape

mydata

mydata_array

num_s=10 #number of servers
num_c=5  #number of clients
num_a=2  #number of apps

#2 different options
#option a:calculate traffic for a specific app
#option b:calculate traffic for a specific server
#the output1 is the series of numbers which indicates the volume of the data transfered in duration of every minute based on the value of ack number
#the output2 is the series of numbers which indicates the volume of the data transfered in duration of every minute based on the value of seq number
#change the value of desired option to 1
option_a=1
option_b=0
app=1 #choose which app you want to calculate traffic for;here we selected app number 1
server=1 #choose which server you want to calculate traffic for;here we selected server number 3
if (option_a):
    list1=np.zeros((1,num_s*num_c),dtype='i') 
    list2=np.zeros((1,num_s*num_c)) 
    list1[0,0]=(app-1)*2

    for i in range((num_a*num_c*num_s)):
      if i+1<(num_s*num_c): #size of list1 is num_s*num_c
          list1[0,i+1]=list1[0,i]+(num_a*2)
    list2=list1+1
    list11=list1.flatten()
    list12=list11.tolist()
    list21=list2.flatten()
    list22=list21.tolist()
    output1=np.sum(mydata_array[list12,:],axis=0) #sum of selected rows for ack
    output2=np.sum(mydata_array[list22,:],axis=0) #sum of selected rows for syn
if (option_b):
    list1=np.zeros((1,num_a*num_c),dtype='i')
    list2=np.zeros((1,num_a*num_c)) 
    list1[0,0]=(server-1)*2*(num_a*num_c)
    for i in range((num_a*num_c*num_s)):
      if i+1<(num_a*num_c): #size of list1 is num_a*num_c
          list1[0,i+1]=list1[0,i]+2
    list2=list1+1
    list11=list1.flatten()
    list12=list11.tolist()
    list21=list2.flatten()
    list22=list21.tolist()
    output1=np.sum(mydata_array[list12,:],axis=0) #sum of selected rows for ack
    output2=np.sum(mydata_array[list22,:],axis=0) #sum of selected rows for syn

np.savetxt("output1.txt",output1,delimiter='')

np.savetxt("output2.txt",output2,delimiter='')